# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Kristjan Greenewald
tagline:             ' Research Scientist '
description:         'A research scientist at the MIT-IBM Watson AI Lab.'
url:                 http://kgreenewald.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Kristjan Greenewald
  url:               https://github.com/kgreenewald
  email:             kristjan.h.greenewald@ibm.com

# Custom vars
version:             1.0.0
